# mvn clean package
# mvn clean package -DskipTests

# docker-compose --version
# docker-compose up
# docker-compose up -d
# docker-compose -f docker-compose-my.yml up
# docker-compose down
# docker-compose restart
# docker-compose ps

# Version
version: '3.1'

# Services
services:
  backend:
    container_name: container_blog_springboot
    image: image_blog_springboot
    restart: on-failure # unless-stopped
    #build: ./  # default Dockefile
    build:
      context: .
      dockerfile: DockerfileBackend
    ports:
      - "4444:4444"
    networks:
      - fullstack_network

# Network
#networks:
#  blog_network:
#    name: blog_network
#    driver: bridge

networks:
  fullstack_network:
    external: true